//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by diplom.rc
//
#define IDD_DLG_ALN                     1
#define IDD_PROPPAGE_PC                 2
#define IDD_PROPPAGE_FILL               3
#define IDD_DLG_DLGBARH                 100
#define IDC_RAD_A                       101
#define IDC_EDIT_PASSNUMB               101
#define IDC_ED_RANG                     101
#define IDC_GROUPBOX2                   102
#define IDC_SPIN_PASS                   102
#define IDC_BORSHADE3                   103
#define IDC_COMBO_ALHO                  103
#define IDC_BTN_A4_H                    104
#define IDC_CHECK_USE_CODING            104
#define IDC_BORSHADE1                   105
#define IDC_EDIT_KEY                    105
#define IDC_ED_L                        105
#define IDC_BTN_A3_H                    106
#define IDC_ED_NUMBER                   106
#define IDC_BTN_A1_H                    107
#define IDC_SPIN_PASS2                  107
#define IDC_BTN_A2_H                    108
#define IDC_ED_M                        108
#define IDC_RAD_D                       109
#define IDC_ED_D                        109
#define IDC_GROUPBOX1                   110
#define IDC_BTN_A1_V                    111
#define IDC_BTN_A2_V                    112
#define IDC_BTN_A3_V                    113
#define IDC_GROUPBOX3                   115
#define IDC_BORSHADE4                   117
#define IDC_BTN_D3_H                    119
#define IDC_GROUPBOX4                   122
#define IDC_BTN_D1_V                    123
#define IDC_BTN_D2_V                    124
#define IDC_BTN_D3_V                    125
#define IDR_MAINFRAME                   128
#define IDR_DIPLOMTYPE                  129
#define IDB_DIB_ABOUT256                133
#define IDB_NEW                         135
#define IDB_OPEN                        136
#define IDB_SAVE                        137
#define IDB_HELP                        140
#define IDB_DUP                         141
#define IDB_REDO                        142
#define IDB_UNDO                        143
#define IDB_PROP                        144
#define IDB_CLEAR                       145
#define IDB_DIB_BKGNDV                  146
#define IDB_DIB_BKGNDH                  146
#define IDB_BMP_ED_FONT                 147
#define IDB_BMP_ED_FNTCLR               148
#define IDB_BMP_ED_FNTUP                149
#define IDB_BMP_ED_FNTDOWN              150
#define IDB_BMP_ED_LIN                  151
#define IDB_BMP_ED_LINCLR               152
#define IDB_BMP_ED_LINTHICK             153
#define IDB_BMP_ED_LINTYP               154
#define IDB_BMP_ED_FIL                  155
#define IDB_BMP_ED_FILCLR               156
#define IDB_BMP_ED_FILTYP               157
#define IDB_BMP_ED_CALC                 158
#define IDB_BMP_ED_ALIGN                162
#define IDB_SNSL_1                      163
#define IDB_SNSL_2                      164
#define IDB_SNSL_3                      165
#define IDB_SNSL_4                      166
#define IDB_SNSL_PC                     167
#define IDB_SNSL_CNCT                   168
#define IDB_SNSL_TXT                    169
#define IDB_SMALLICONS                  170
#define IDB_LARGEICONS                  171
#define IDB_STATEICONS                  172
#define IDB_LOC_REM                     173
#define IDB_LOC_ED                      174
#define IDB_LOC_ADD                     175
#define IDB_HCH                         176
#define IDC_CURSOR_ADD                  178
#define IDD_DIALOG1                     179
#define IDB_BMP_A1_H                    180
#define IDB_BMP_A2_H                    181
#define IDB_BMP_A3_H                    182
#define IDB_BMP_A1_V                    183
#define IDB_BMP_A2_V                    184
#define IDB_BMP_A3_V                    185
#define IDB_BMP_A4_H                    186
#define IDB_BMP_D1_H                    187
#define IDB_BMP_D2_H                    188
#define IDB_BMP_D3_H                    189
#define IDB_BMP_D1_V                    190
#define IDB_BMP_D2_V                    191
#define IDB_BMP_D3_V                    192
#define IDC_CURSOR_GLUMOV               193
#define IDD_PROPPAGE_TXT                195
#define IDD_PROPPAGE_LINE               196
#define IDD_DLG_BRIG                    197
#define IDB_LOC_ACCEPT                  198
#define IDB_BITMAP1                     199
#define IDB_BMP_STOP                    199
#define IDD_DLG_SCALE                   200
#define IDB_BMP_ED_STEP                 201
#define IDB_BMP_ED_STEPMODE             202
#define IDD_DIALOG_SCSUB                203
#define IDC_BTN_A4_V                    204
#define IDB_BITMAP_APP                  204
#define IDC_BTN_D1_H                    211
#define IDC_BTN_D2_H                    212
#define ICM_ED_FONT                     500
#define ICM_ED_FNTCLR                   501
#define ICM_ED_ALIGN                    502
#define ICM_ED_FNTDOWN                  503
#define ICM_ED_LIN                      504
#define ICM_ED_LINCLR                   505
#define ICM_ED_LINTHICK                 506
#define ICM_ED_LINTYP                   507
#define ICM_ED_FIL                      508
#define ICM_ED_FILCLR                   509
#define ICM_ED_FILTYP                   510
#define ICM_ED_CALC                     511
#define ICM_ED_STOP                     512
#define ID_LOC_ADD                      700
#define ID_LOC_REM                      701
#define ID_LOC_ED                       702
#define ID_LOC_ACCEPT                   703
#define ID_CBN_SCALE                    999
#define IDC_COMBO1                      1001
#define IDC_ED_NAME                     1004
#define IDC_ED_TEXT                     1005
#define IDC_COMBO_PATTERN               1006
#define IDC_COMBO_PATTERN2              1008
#define IDC_COMBO_WEIGHT                1008
#define IDC_COMBO_PATTERN3              1009
#define IDC_COMBO_FONCLR                1010
#define IDC_COMBO_CLR                   1011
#define IDC_BTN_CLREXT                  1012
#define IDC_BTN_CLREXTBK                1013
#define IDC_RAD_PRIOR                   1013
#define IDC_RAD_NOPRIOR                 1014
#define IDC_RAD_LABELED                 1015
#define IDC_EDIT_NUMBER                 1016
#define IDC_SPIN1                       1018
#define IDC_SLIDER1                     1019
#define IDC_RADIO1                      1020
#define IDC_RADIO2                      1021
#define IDC_EDIT1                       1022
#define IDC_RAD_SELF                    1023
#define IDC_RAD_GLOB                    1024
#define IDC_LIST_DP                     1024
#define IDC_CHECK1                      1026
#define ID_APPABOUT                     32771
#define ID_FASTACCESS_SHOW              32773
#define ID_TOOLALN_SHOW                 32774
#define ID_EDIT_DUP                     32776
#define ID_EDIT_UNSELECTALL             32777
#define ID_EDIT_INV                     32778
#define ID_VIEW_PRIVSCALE               32779
#define ID_VIEW_100                     32780
#define ID_VIEW_PAGEW                   32781
#define ID_VIEW_PAGE                    32782
#define ID_VIEW_200                     32783
#define ID_VIEW_50                      32784
#define ID_VIEW_LINE                    32785
#define ID_V                            32786
#define ID_VIEW_GRID                    32787
#define ID_VIEW_GUIDLINES               32788
#define ID_VIEW_CNCTPOINTS              32789
#define ID_S                            32790
#define ID_BR_BRIG                      32791
#define ID_BR_ELEMENTS                  32793
#define ID_BR_SOLVE                     32794
#define ID_BR_STEPGRID                  32795
#define ID_BR_STEPGUID                  32796
#define ID_W                            32797
#define ID_WINDOW_CLOSEALL              32798
#define ID_WINDOW_NEXT                  32801
#define ID_WINDOW_PRIV                  32803
#define ID_PRIV_PANE                    32803
#define ID_APP_WINDOW                   32804
#define ID_VIEW_LOCALTOOL               32805
#define ID_VIEW_TEXTURE                 32806
#define ID_VIEW_SAVEOPT                 32807
#define ID_VIEV_SVEDESKTOP              32809
#define ID_VIEW_SIMPLEVIEW              32810
#define ID_VIEW_ARROW                   32811
#define ID_SC_ALIGMENT                  32812
#define ID_SC_CENTER                    32813
#define ID_SC_BACK                      32814
#define ID_SC_FORWARD                   32815
#define ID_CTX_PROPERTY                 32817
#define ID_BR_SERVIS                    32818
#define ID_BR_UNSERVIS                  32819
#define ID_BR_LABEL                     32820
#define ID_CLC_EQREST                   32821
#define ID_ED_SELECTPC                  32822
#define ID_ED_SELECTCNCT                32823
#define ID_SC_FILL_LM                   32824
#define ID_SC_CRERNG                    32825
#define ID_EDIT_SCALE                   32826
#define ID_SC_ALNGUID                   32827
#define ID_FILE_REVERT                  32828
#define ID_ED_SELDBL                    32829
#define ID_CLC_CONNECT                  32830
#define ID_ED_UNHILITE                  32831
#define ID_CLC_CTYPE                    32832
#define ID_CLC_CINT                     32833
#define ID_ED_SELECT_HIGH               32834
#define ID_CLC_NPATHS                   32835
#define ID_CLC_TSIMPL                   32836
#define ID_CLC_RUN                      32837
#define ICM_ED_SINGLESTEP               32838
#define ICM_ED_STEPMODE                 32839
#define ID_ED_SELECTPC_DP               32840
#define ID_ED_SELECTPC_HIGH             32841
#define ID_ED_SEL_CDP                   32843
#define ID_ED_SEL_HIGH                  32844
#define ID_ED_SEL_SUBSCH                32845
#define ID_CLC_TSOFIST                  32846
#define ID_E                            32847
#define ID_ED_SELDBL_MAX                32848
#define ID_FILE_EXPORT                  32849
#define ID_CLC_ARNG                     32850
#define ID_MODE_BRIG                    32905

#define ID_CTX_REPORT                   32851

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32852
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
